routes/web.php
<?php

Route::group(['prefix' => 'admin','namespace'=>'Admin','middleware'=>['web','auth']], function () {
    Route::get('/', 'HomeController@index')->name('admin.home');
    Route::resource('categories','CategoryController');
    Route::resource('products','ProductController');
    Route::get('callback','CallbackController@index')->name('admin.callback');
    Route::delete('products/remove_item/{product}/{gallery}','ProductController@removeItem')->name('remove.gallery.item');
});
    Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::post('/callback', 'HomeController@callback')->name('callback');
Route::get('/products', 'HomeController@products')->name('products');
Route::get('/product/{product}', 'HomeController@productById')->name('product.by.id');
Route::get('/products/{category}', 'HomeController@productsByCategory')->name('products.by.category');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Product
 * @package App
 * @property $title;
 * @property $content;
 * @property $code;
 * @property $price;
 * @property $description;
 */
class Product extends Model
{
    protected $fillable = [
        'title',
        'main_image',
        'description',
        'code',
        'user_id',
        'price',
    ];

    public function user()
    {
        return $this->hasOne(User::class);
    }

    public function categories()
    {
        return $this->hasOne(Category::class, 'id', 'category_id');
    }

    public function gallery()
    {
        return $this->hasMany(Gallery::class);
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Gallery;
use App\Http\Requests\ProductCreateRequest;
use App\Product;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class ProductController extends Controller
{
    private $pageName = "Товары";

    public function index()
    {
        $pageName = $this->pageName;
        $products = Product::with('categories')->get();
        return view('admins.products.index', compact('pageName', 'products'));
    }


    public function create()
    {
        $categories = self::getCategories();
        return view('admins.products.create', compact('categories'));
    }

    public static function SaveImage($image, $folder = 'product_images', $disk = 'public')
    {
        return \Storage::disk($disk)->put($folder, $image);
    }

    public function store(ProductCreateRequest $request)
    {

        /**
         * @var Category $category
         */
        $category = Category::getCategory($request);
        $request->main_image = self::SaveImage($request->file('main_image'));

        $result = $category->products()->create([
            'user_id' => \Auth::id(),
            'title' => $request->title,
            'main_image' => $request->main_image,
            'price' => $request->price,
            'code' => $request->code,
            'description' => $request->description,
        ]);

        foreach ($request->file('gallery') as $file) {
            $gallery['product_id'] = $result->id;
            $gallery['filename'] = self::SaveImage($file, 'product_images/gallery');
            Gallery::create($gallery);
        }

        \Session::flash('message', 'Товар был создан успешно');
        return redirect()->route('products.index');
    }

    public function show(Product $product)
    {

        $product = $product->load('categories', 'gallery');
        return view('admins.products.show', compact('product'));
    }


    public function edit(Product $product)
    {
        $product = $product->with('gallery')->first();
        $categories = self::getCategories();
        return view('admins.products.edit', compact('categories', 'product'));
    }

    public static function getCategories()
    {
        return Category::get(['name', 'id'])->pluck('name', 'id')->toArray();

    }

    public function removeItem($product, $gallery)
    {
        try {
            $product = Product::find($product)->with('gallery')->get()->first();
            $image = $product->gallery->where('id', $gallery)->first();
            $image_path = $image->filename;
            $image->delete();
            Storage::disk('public')->delete($image_path);
            return redirect()->back();
        } catch (\Error $error) {
            \Session::flash('error', $error);
        }
    }

    public static function deleteImage($file)
    {
        Storage::disk('public')->delete($file);
    }

    public function update(Request $request, Product $product)
    {
        /**
         * @var Category $category
         */
        $category = Category::getCategory($request);
        if ($request->file('main_image')) {
            $image = self::SaveImage($request->file('main_image'));
            self::deleteImage($product->main_image);
            $request->main_image = $image;
        }
        $product->category_id = $category->id;
        $product->update([
            'title' => $request->title,
            'main_image' => $request->main_image,
            'price' => $request->price,
            'code' => $request->code,
            'description' => $request->description,
        ]);
        if ($request->file('gallery')) {
            foreach ($request->file('gallery') as $file) {
                $gallery['product_id'] = $product->id;
                $gallery['filename'] = self::SaveImage($file, 'product_images/gallery');
                Gallery::create($gallery);
            }
        }
        return redirect()->back();
    }


    public function destroy(Product $product)
    {
        $image = $product->main_image;
        $result = $product->delete();
        if ($result) {
            Storage::disk('public')->delete($image);
        }
        return redirect()->route('products.index');
    }
}

resources/views/admins/products/create.blade.php
@extends('admins.layouts.app')

@section('content')

    <div class="col-12 col-md-9">
        <div class="row">
            <div class="col-md-12">
                <a class="m-2 float-left btn btn-primary" href="{{route('products.index')}}">Back</a>
            </div>
            <div class="col-md-12">
                {{Form::open(['url'=>route('products.store'),'method'=>'post','files'=>true])}}
                <div class="form-group">
                    {{Form::label('category','Категории')}}
                    {{Form::select('category', $categories,$categories,['class'=>'form-control'])}}
                </div>
                <div class="form-group">
                    {{Form::label('main_image','Главное Изображение товара')}}
                    {{Form::file('main_image',['class'=>"form-control",'multiple' => false])}}
                </div>
                <div class="form-group">
                    {{Form::label('gallery','Галерея')}}
                    {{Form::file('gallery[]',['class'=>"form-control",'multiple' => true])}}
                </div>
                <div class="form-control-file"></div>
                <div class="form-group">
                    {{Form::label('name','Название Товара')}}
                    {{Form::text('title',old('title'),['class'=>'form-control'])}}
                </div>

                <div class="form-group">
                    {{Form::label('ordered','Код Товара')}}
                    {{Form::text('code',old('code'),['class'=>'form-control'])}}
                </div>
                <div class="form-group">
                    {{Form::label('price','Цена Товара')}}
                    {{Form::number('price',old('price'),['class'=>'form-control'])}}
                </div>
                <div class="form-group">
                    {{Form::label('description','Описание Товара')}}
                    <textarea name="description" class="form-control" id="" cols="30" rows="10"></textarea>
                </div>
                {{Form::submit('Сохранить Товар',['class'=>'btn btn-success'])}}
                {{Form::close()}}
            </div>
        </div>
    </div>

@stop

resources/views/admins/products/edit.blade.php
@extends('admins.layouts.app')

@section('content')

    <div class="col-12 col-md-9">
        <div class="row">
            <div class="col-md-12">
                <a class="m-2 float-left btn btn-primary" href="{{route('products.index')}}">Back</a>
            </div>
            <div class="col-md-12">
                {{Form::open(['url'=>route('products.update',$product->id),'method'=>'put','files'=>true])}}
                <div class="form-group">
                    {{Form::label('category','Категории')}}
                    {{Form::select('category', $categories,$product->category_id?$product->category_id:old('category_id'),['class'=>'form-control'])}}
                </div>
                <div class="row">
                    <div class="form-group col-md-5">
                        {{Form::label('main_image','Главное Изображение товара')}}
                        {{Form::file('main_image',['class'=>"form-control",'multiple' => false])}}
                    </div>
                    <div class="form-group col-md-6">
                        <img class="col-md-12" src="{{getImage($product->main_image)}}" alt="">
                    </div>
                </div>


                <div class="form-group">
                    {{Form::label('title','Название Товара')}}
                    {{Form::text('title',$product->title,['class'=>'form-control'])}}
                </div>

                <div class="form-group">
                    {{Form::label('code','Код Товара')}}
                    {{Form::text('code',$product->code,['class'=>'form-control'])}}
                </div>
                <div class="form-group">
                    {{Form::label('price','Цена Товара')}}
                    {{Form::number('price',$product->price,['class'=>'form-control'])}}
                </div>
                <div class="form-group">
                    {{Form::label('description','Описание Товара')}}
                    <textarea name="description" class="form-control" id="description" cols="30"
                              rows="10">{{$product->description}}</textarea>
                </div>

                <div class="row">
                    <div class="form-group col-md-6">
                        <div class="form-group col-md-5">
                            {{Form::label('gallery','Галерея товара')}}
                            {{Form::file('gallery[]',['class'=>"form-control",'multiple' => true])}}
                        </div>
                        <div class="form-group col-md-5">
                            {{Form::submit('Сохранить Товар',['class'=>'btn btn-success'])}}
                            {{Form::close()}}
                        </div>

                    </div>
                    <div class="form-group col-md-6">
                        <div class="row">

                                    <div class="row">
                                        @forelse($product->gallery as $image)
                                            <div class="col-md-4">
                                                <img width="90px" src="{{getImage($image->filename)}}"
                                                     alt="{{$product->title}}">
                                                {{Form::open(['url'=>route('remove.gallery.item',[$image->product_id,$image->id]),'method'=>'delete'])}}
                                                {{Form::submit('X',['class'=>'btn btn-sm btn-danger'])}}
                                                {{Form::close()}}

                                            </div>
                                        @empty
                                            Галереи не существует
                                        @endforelse
                                    </div>
                        </div>
                    </div>
                </div>



            </div>
        </div>
    </div>

@stop

resources/views/admins/products/index.blade.php
@extends('admins.layouts.app')



@section('content')

</span>
    <div class="col-12 col-md-9">
        <div class="row">
            <div class="col-md-12">
                <h2 class="m-2 float-left text-uppercase">{{$pageName}}</h2>
                <a class="m-2 float-right btn btn-success" href="{{route('products.create')}}">Создать новый товар</a>
            </div>

            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Title</th>
                    <th>Image</th>
                    <th>Category</th>
                    <th>Price</th>
                    <th>Code</th>
                    <th width="280px">Actions</th>
                </tr>
                </thead>
                <tbody>
                @forelse ($products as $product)
                    <tr>
                        <td>{{$loop->iteration}}</td>
                        <td><a href="{{route('products.show',$product->id)}}">{{$product->title}}</a></td>
                        <td>
                            <img width="100px" src="{{getImage($product->main_image)}}" alt="{{$product->title}}">
                        </td>
                        <td><a href="{{route('categories.show',$product->categories->id)}}">{{$product->categories->name}}</a></td>
                        <td>{{$product->price}}/td>
                        <td>{{$product->code}}</td>
                        <td>
                            <a href="{{route('products.show',$product->id)}}" class="btn btn-primary">Show</a>
                            <a href="{{route('products.edit',$product->id)}}" class="btn btn-warning">Edit</a>
                            {{Form::open(['url'=>route('products.destroy',$product->id),'method'=>'delete','style'=>'display:inline'])}}
                                {{Form::submit('Delete',['class'=>'btn btn-danger'])}}
                            {{Form::close()}}
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="7"><p class="text-center text-uppercase m-5">No products... <a
                                    href="{{route('products.create')}}">Create?</a></p></td>
                    </tr>
                @endforelse

                </tbody>
            </table>
        </div>
    </div>

@stop

resources/views/admins/products/show.blade.php
@extends('admins.layouts.app')



@section('content')
    <div class="col-12 col-md-9">
        <div class="row">
            <div class="col-md-12">
                <a class="m-2 float-left btn btn-primary" href="{{route('products.index')}}">Back</a>
            </div>
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-6">
                        <strong>Название:</strong>
                        <h2 class="font-weight-bold">{{$product->title}}</h2>
                        <strong>Цена:</strong><h4 class="font-weight-bold">{{$product->price}}</h4>
                        <strong>Код:</strong><h4 class="font-weight-bold">{{$product->code}}</h4>
                        <div class="col-md-12">
                            <div class="text-left">
                                {!! $product->description  !!}
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <img width="375px" src="{{getImage($product->main_image)}}" alt="{{$product->title}}">
                        <div class="col-md-12">
                            <div class="row">
                                @forelse($product->gallery as $image)
                                    <div class="col-md-4">
                                        <img width="90px" src="{{getImage($image->filename)}}" alt="{{$product->title}}">
                                    </div>
                                @empty
                                    Галереи не существует
                                @endforelse
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop