routes/web.php
<?php

Route::group(['prefix' => 'admin','namespace'=>'Admin','middleware'=>['web','auth']], function () {
    Route::get('/', 'HomeController@index')->name('admin.home');
    Route::resource('categories','CategoryController');
    Route::resource('products','ProductController');
    Route::get('callback','CallbackController@index')->name('admin.callback');
    Route::delete('products/remove_item/{product}/{gallery}','ProductController@removeItem')->name('remove.gallery.item');
});
    Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::post('/callback', 'HomeController@callback')->name('callback');
Route::get('/products', 'HomeController@products')->name('products');
Route::get('/product/{product}', 'HomeController@productById')->name('product.by.id');
Route::get('/products/{category}', 'HomeController@productsByCategory')->name('products.by.category');

resources/views/admins/partials/errors.blade.php
@if(isset($errors))
    <div class="container">
    @foreach ($errors->all() as $error)
        <div class="alert alert-danger">
            <strong>Внимание!</strong>
            {{$error }}
        </div>
    @endforeach
    </div>
@endif

resources/views/admins/partials/flashes.blade.php
@if(Session::has('message'))
    <div class="container">
        <div class="alert alert-primary">
            <strong>Внимание!</strong>
            {{ Session::get('message') }}
        </div>
    </div>
@endif

resources/views/admins/partials/sidebar.blade.php
<div class="col-6 col-md-3 sidebar-offcanvas" id="sidebar">
    <div class="list-group">
        <a href="{{route('products.index')}}" class="list-group-item {{isActiveRoute('products.index')}} ">Товар</a>
        <a href="{{route('categories.index')}}"
           class="list-group-item {{isActiveRoute('categories.index')}} ">Категории</a>
        <a href="{{route('admin.callback')}}" class="list-group-item {{isActiveRoute('admin.callback')}} ">Перезвонить</a>
    </div>
</div><!--/span-->